---
# tasks file for nginx-webserver
- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: "Install Nginx to version {{ nginx_version }}"
  apt:
    name: "nginx={{ nginx_version }}"
    state: present

- name: Copy the Nginx configuration file to the host
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ web_server_config_name }}"
  
- name: Create link to the new config to enable it
  file:
    dest: "/etc/nginx/sites-enabled/{{ web_server_config_name }}"
    src: "/etc/nginx/sites-available/{{ web_server_config_name }}"
    state: link

- name: Create Nginx directory
  ansible.builtin.file:
    path: "{{ nginx_server_directory }}"
    state: directory
    owner: www-data
    group: www-data

- name: Copy index.html to the Nginx directory
  copy:
    src: files/index.html
    dest: "{{ nginx_server_directory }}/index.html"
    owner: www-data
    group: www-data
  notify: Reload the Nginx service